---
- name: Ensure application is deployed
  hosts: prod

  become: true
  vars_files:
    - "files/secrets/devops.yml"

  tasks:
    - block:
      - name: Check that you can connect to webpage
        uri:
          url: http://{{ ip_addr_prod }}:{{ port_app }}
        retries: 8
        delay: 100

      - name: Check webservice application production
        uri:
          url: http://{{ ip_addr_prod }}:{{ port_app }}/health
          method: GET
        retries: 8
        delay: 100
      tags:
        - prod
