version: "3.7"
services:
 # db 
  db-sahib:
    hostname: "db-sahib"
    image: "mysql:5.7"
    container_name: "db-sahib"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_DATABASE: "battleboat"
      MYSQL_USER: "battleuser"
      MYSQL_PASSWORD: "battlepass"
    ports:
      - "3306:3306"
    networks:
      - "battleboat"
    restart: always

  # fake-backend
  battle-sahib:
    hostname: "battle-sahib"
    image: "sahibmartial/fake-backend:jenkinsCI"
    container_name: "battle-sahib"
    environment:
      DATABASE_HOST: "db-sahib"
      DATABASE_PORT: "3306"
      DATABASE_USER: "battleuser"
      DATABASE_PASSWORD: "battlepass"
      DATABASE_NAME: "battleboat"
    ports:
      - "8181:3000"
    networks:
      - "battleboat"
    restart: always
    depends_on:
      - "db-sahib"
    volumes:
      - ./battleboat/:/etc/backend/static

networks:
  battleboat:
    name: "battleboat"
    
volumes:
  db-data:
